next:
  - command: create
    help: create a new garden
    next:
      - argument: ['name']
        type: str
        help: name of the garden
      - argument: ['--use']
        action: store_true
        help: automatically switch to the garden after creation

  - command: remove
    help: remove a garden
    next:
      - argument: ['name']
        type: str
        help: name of the garden
      - argument: [--force]
        help: remove garden with all its beds

  - command: use
    help: select a garden to work with
    next:
      - argument: ['name']
        type: str
        help: name of the garden

  - command: new
    help: create a new garden object
    next:
      - command: bed
        help: create a new garden bed
        next:
          - argument: [-s, --size]
            type: int
            required: true
            help: the size (max capacity) of the garden bed

  - command: seed
    help: seed a garden bed with vegetables
    next:
      - argument: [-b, --bed]
        dest: bed_id
        type: str
        required: true
        help: the number of garden bed
      - argument: [-n, --name]
        type: str
        required: true
        help: the name of vegetable to seed
      - argument: [-c, --count]
        type: int
        required: true
        help: the number of vegetables to seed

  - command: list
    help: list available gardens or garden objects
    group:
      required: false
    next:
      - command: bed
        help: list garden beds
        next:
          - argument: [--details]
            action: store_true
            help: list garden beds with all their plants

  - command: water
    help: water a garden bed
    next:
      - argument: [-b, --bed]
        dest: bed_id
        type: str
        required: true
        help: the number of garden bed to water
      - argument: [--intensive]
        action: store_true
        help: with intensive watering, plants will grow faster
