next:
  - command: generate
    next:
      - argument: [--name]
        type: str
      - argument: [--config]
        type: str
      - argument: [--dir]
        type: str
      - argument: [--force]
        action: store_true
